name: PetroglyphGameInfrastructure Build & Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-test-core:
    name: Build & Test PetroGlyph.Games.EawFoc
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    
    env:
        solution: 'PetroGlyphGameInfrastructure.sln'
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        
    - name: Build
      run: dotnet build ${{ env.solution }} -c Release
        
    - name: Test
      run: dotnet test ${{ env.solution}} -c Release