name: CI/CD Main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency: deploy-tagging

jobs:

# Builds and tests the solution.
  build-test:
    uses: AlamoEngine-Tools/PetroglyphGameInfrastructure/.github/workflows/test.yml@master

# Creates a new tag based on git history messages between the [latest-tag - HEAD].
  tag:
    needs: build-test
    uses: AlamoEngine-Tools/PetroglyphGameInfrastructure/.github/workflows/tag.yml@master
    with:
      create: ${{ github.event_name == 'push' }}

# Packs and deploys artifacts.
  pack-deploy:
    if: ${{ github.event_name == 'push' && needs.tag.outputs.part != '' }} # Only deploy if we have a new tag.
    needs: tag
    uses: AlamoEngine-Tools/PetroglyphGameInfrastructure/.github/workflows/pack-deploy.yml@master
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
    with:
      package-version: ${{needs.tag.outputs.new-tag}}

  # Create a GitHub Release.
  release:
    needs: pack-deploy
    uses: AlamoEngine-Tools/PetroglyphGameInfrastructure/.github/workflows/release.yml@master
    with:
      tag: ${{needs.tag.outputs.new-tag}}