name: Release 

on:
  workflow_call:
    inputs:
      prerelease:
        required: false
        type: boolean
      tag:
        required: true
        type: string

jobs:
  release:
    name: GitHub Release 
    runs-on: ubuntu-latest
       
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ inputs.tag }}
          prerelease: ${{ inputs.prerelease }}
          generate_release_notes: true