name: Tag Release

on:
  workflow_call:
    outputs:
      new-tag:
        value: ${{ jobs.tag.outputs.new-tag }}
      part:
        value: ${{ jobs.tag.outputs.part }}
    inputs:
      create:
        required: false
        type: boolean

jobs:
  
  tag:
    name: Tag Repository
    runs-on: ubuntu-latest
    outputs:
      new-tag: ${{ steps.create-tag.outputs.new_tag }}
      part: ${{ steps.create-tag.outputs.part }}
        
    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"

    - id: create-tag
      name: Create Release Tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_BRANCHES: main,master
        DRY_RUN: ${{ ! inputs.create }} # mind, this is inverted!
        DEFAULT_BUMP: patch
        WITH_V: false # cannot use, because we need a non-V output string. 