name: Build & Test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-test:
    name: Build & Test
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
        
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
        
      - name: Build & Test in Release Mode
        run: dotnet test --configuration Release --logger "GitHubActions"

      - name: Build & Test .NET Framework
        if: matrix.os == 'windows-latest'
        run: dotnet test --configuration Release -f net48 --logger "GitHubActions"